version: "3"

services:
  web:
    build:
      context: ./.docker/php
    restart: always
    volumes:
      - .:/var/www/html:delegated
    ports:
      - "80"

  db:
    image: bitnami/mariadb:10.5
    restart: always
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal

volumes:
  data-volume:
